<script lang="ts">
	import LeftHex from './components/LeftHex.svelte';
	import RightHex from './components/RightHex.svelte';
</script>

<div class="absolute flex flex-wrap items-center w-full stroke-primary-500 stroke-2 fill-none">
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
	<LeftHex />
	<RightHex />
</div>
